context:
  version: "10.4.6"

package:
  name: storybook
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/storybook/-/storybook-${{ version }}.tgz
  sha256: 5c87b57113a5d5d51ddc8a5d962a768cf86103123bc516fa188717a3411a90df

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - storybook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Storybook's CLI - install, dev, build, upgrade, and more"
  homepage: https://github.com/storybookjs/storybook
  repository: https://github.com/storybookjs/storybook

extra:
  recipe-maintainers:
    - danielnachun
