context:
  version: "10.4.1"

package:
  name: storybook
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/storybook/-/storybook-${{ version }}.tgz
  sha256: e7c3340ac492fcfe57ef814a714d85b524f8b265aacb246aaf7981bc69823d10

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - storybook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Storybook's CLI - install, dev, build, upgrade, and more"
  homepage: https://github.com/storybookjs/storybook
  repository: https://github.com/storybookjs/storybook

extra:
  recipe-maintainers:
    - danielnachun
