context:
  version: "9.1.12"

package:
  name: storybook
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/storybook/-/storybook-${{ version }}.tgz
  sha256: 378d2a1760d59e0e9bf66baef28a94fe4a2ac97ad0027ba691aaed96de92a91c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - storybook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Storybook's CLI - install, dev, build, upgrade, and more"
  homepage: https://github.com/storybookjs/storybook
  repository: https://github.com/storybookjs/storybook

extra:
  recipe-maintainers:
    - danielnachun
