context:
  version: "8.6.8"

package:
  name: storybook
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/storybook/-/storybook-${{ version }}.tgz
  sha256: 4e73e3e87ab0c7aa9484482765df29b21febe6e21f9c9099e505890c3bc13dc7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - storybook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Storybook's CLI - install, dev, build, upgrade, and more"
  homepage: https://github.com/storybookjs/storybook
  repository: https://github.com/storybookjs/storybook

extra:
  recipe-maintainers:
    - danielnachun
