context:
  version: "10.3.1"

package:
  name: storybook
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/storybook/-/storybook-${{ version }}.tgz
  sha256: c9a84908afac639d32a3c730ba90857655bedc91506dde40ec93da4a4eb90b11

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - storybook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Storybook's CLI - install, dev, build, upgrade, and more"
  homepage: https://github.com/storybookjs/storybook
  repository: https://github.com/storybookjs/storybook

extra:
  recipe-maintainers:
    - danielnachun
